imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
  dbal:
        driver: pdo_mysql
        host: 127.0.0.1
        port: null
        dbname: rentTest
        user: rentTest
        password: rentTest

liip_functional_test:
  cache_sqlite_db: true