security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: rentbundle_secure_check
                login_path: rentbundle_secure_login
            logout:
                path:   rentbundle_secure_logout
                target: rentbundle_secure_login
            oktolab: false
            provider: in_memory