security:
    encoders:
        Oktolab\Bundle\RentBundle\Entity\Security\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hub_authenticator:
            id: oktolab.hub_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
            pattern:  ^/secure/login$
            security: false

        secured_area:
            pattern:    ^/
            logout:
                path:   rentbundle_secure_logout
                target: rentbundle_secure_login
            oktolab: true
            provider: hub_authenticator
            form_login:
                login_path: rentbundle_secure_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
