security:
    encoders:
        Oktolab\Bundle\RentBundle\Entity\Security\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hub_authenticator:
            id: oktolab.hub_user_provider
#        hub_authenticator2:
#            entity: { class: OktolabRentBundle:Security\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#            oktolab: true
#            provider: hub_authenticator

        login:
            pattern:  ^/secure/login$
            security: false

        secured_area:
            pattern:    ^/
#            form_login:
#                check_path: rentbundle_secure_check
#                login_path: rentbundle_secure_login
            logout:
                path:   rentbundle_secure_logout
                target: rentbundle_secure_login
            oktolab: true
            provider: hub_authenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
