security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Bprs\UserBUndle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        database:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            pattern:    /
            http_basic: ~
            form_login:
                login_path: bprs_user_login
                check_path: bprs_user_login_check
                default_target_path: homepage
                csrf_provider: security.csrf.token_manager
                default_target_path: /
            logout:
                path: bprs_user_logout
                target: /
            anonymous: ~

    access_control:
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /, roles: ROLE_USER }
        - { path: /backend/, roles: ROLE_ADMIN}
