security:
    encoders:
        Oktolab\Bundle\RentBundle\Entity\Security\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hub_authenticator:
            id: oktolab.hub_user_provider

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: rentbundle_secure_login
            logout:
                path:   rentbundle_secure_logout
                target: rentbundle_secure_login
            oktolab: true
            provider: hub_authenticator

    access_control:
        - { path: ^/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
