parameters:
    oktolab.event_manager.class:                       Oktolab\Bundle\RentBundle\Model\Event\EventManager
    oktolab.event_form.class:                          Oktolab\Bundle\RentBundle\Form\EventType
    oktolab.event_calendar_inventory_aggregator.class: Oktolab\Bundle\RentBundle\Model\Event\Calendar\InventoryAggregator
    oktolab.event_calendar_inventory.class:            Oktolab\Bundle\RentBundle\Model\Event\Calendar\InventoryTransformer
    oktolab.event_calendar_timeblock_aggregator.class: Oktolab\Bundle\RentBundle\Model\Event\Calendar\TimeblockAggregator
    oktolab.event_calendar_timeblock.class:            Oktolab\Bundle\RentBundle\Model\Event\Calendar\TimeblockTransformer
    oktolab.event_calendar_event_aggregator.class:     Oktolab\Bundle\RentBundle\Model\Event\Calendar\EventAggregator
    oktolab.event_calendar_event.class:                Oktolab\Bundle\RentBundle\Model\Event\Calendar\EventTransformer
    oktolab.inventory_transformer_cache_listener:      Oktolab\Bundle\RentBundle\EventListener\InventoryTransformerCacheListener

services:
    oktolab.event_manager:
        class:      %oktolab.event_manager.class%
        arguments:  [ @doctrine.orm.entity_manager, @?logger ]
        calls:
            - [ addRepository, [ "Event", @oktolab.orm.event_repository ] ]
            - [ addRepository, [ "Item", @oktolab.orm.item_repository ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]

    oktolab.form.event:
        class:            %oktolab.event_form.class%
#        calls:
#            - [
        tags:
            - { name: form.type, alias: OktolabRentBundle_Event_Form }

    oktolab.event_calendar_inventory_aggregator:
        class:  %oktolab.event_calendar_inventory_aggregator.class%
        public: false
        calls:
            - [ addRepository, [ "Set", @oktolab.orm.set_repository ] ]
            - [ addRepository, [ "Item", @oktolab.orm.item_repository ] ]
            - [ addRepository, [ "Category", @oktolab.orm.category_repository ] ]

    oktolab.event_calendar_inventory:
        class:      %oktolab.event_calendar_inventory.class%
        arguments:  [ @oktolab.event_calendar_inventory_aggregator, @oktolab.cache ]

    oktolab.event_calendar_timeblock_aggregator:
        class:  %oktolab.event_calendar_timeblock_aggregator.class%
        public: false
        calls:
            - [ addRepository, [ "Timeblock", @oktolab.orm.timeblock_repository ] ]

    oktolab.event_calendar_timeblock:
        class:      %oktolab.event_calendar_timeblock.class%
        arguments:  [ @oktolab.event_calendar_timeblock_aggregator, @oktolab.event_calendar_timeblock_cache ]

    # 'Cause there is no way to delete Keys by Regex or Pre-/Suffix.
    oktolab.event_calendar_timeblock_cache:
        class:      %oktolab.cache.class%
        public:     false
        arguments:  [ %kernel.cache_dir% ]

    oktolab.event_calendar_event_aggregator:
        class:  %oktolab.event_calendar_event_aggregator.class%
        public: false
        calls:
            - [ addRepository, [ "Event", @oktolab.orm.event_repository ] ]

    oktolab.event_calendar_event:
        class:      %oktolab.event_calendar_event.class%
        arguments:  [ @oktolab.event_calendar_event_aggregator, @router, @oktolab.event_manager, @oktolab.cache ]

    oktolab.inventory_transformer_cache_listener:
        class:     %oktolab.inventory_transformer_cache_listener%
        arguments: [ @oktolab.cache ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postUpdate }