parameters:
    oktolab.orm.object_repository.class: Doctrine\Common\Persistence\ObjectRepository

services:
    oktolab.orm.event_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Event ]

    oktolab.orm.item_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Inventory\Item ]

    oktolab.orm.set_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Inventory\Set ]

    oktolab.orm.category_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Inventory\Category ]

    oktolab.orm.timeblock_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Timeblock ]