services:
    oktolab.presavelistener:
      class: Oktolab\Bundle\RentBundle\EventListener\LogListener
      arguments: [@?logger]
      tags:
        - { name: logger, channel: main}
        - { name: doctrine.event_listener, event: prePersist }
    oktolab.postsavelistener:
      class: Oktolab\Bundle\RentBundle\EventListener\LogListener
      tags:
        - { name: doctrine.event_listener, event: postPersist }