parameters:
    oktolab.event_manager.class: Oktolab\Bundle\RentBundle\Model\EventManager

services:
    oktolab.presavelistener:
      class: Oktolab\Bundle\RentBundle\EventListener\LogListener
      arguments: [@?logger]
      tags:
        - { name: logger, channel: main}
        - { name: doctrine.event_listener, event: prePersist }

    oktolab.postsavelistener:
      class: Oktolab\Bundle\RentBundle\EventListener\LogListener
      arguments: [@?logger]
      tags:
        - { name: logger, channel: main}
        - { name: doctrine.event_listener, event: postPersist }

    oktolab.event_manager:
      class: %oktolab.event_manager.class%
      arguments:  [ @doctrine.orm.entity_manager, @?logger ]
      tags:
        - { name: logger, channel: main }