parameters:
    # common service-classes
    oktolab.cache.class:                      Doctrine\Common\Cache\PhpFileCache
    oktolab.presavelistener.class:            Oktolab\Bundle\RentBundle\EventListener\LogListener
    oktolab.postsavelistener.class:           Oktolab\Bundle\RentBundle\EventListener\LogListener
    oktolab.twig.attachment.extension.class:  Oktolab\Bundle\RentBundle\Extension\AttachmentExtension
    oktolab.twig.pager.extension.class:       Oktolab\Bundle\RentBundle\Extension\AuiPaginationExtension
    oktolab.item_import_manager.class:        Oktolab\Bundle\RentBundle\Model\ItemImportManager
    oktolab.item_csv_importer.class:          Oktolab\Bundle\RentBundle\Model\ItemCsvParser
    oktolab.contact_provider.class:           Oktolab\Bundle\RentBundle\Model\ContactProvider
    oktolab.costunit_provider.class:          Oktolab\Bundle\RentBundle\Model\CostUnitProvider
    oktolab.hub_fetch_service.class:          Oktolab\Bundle\RentBundle\Model\HubFetchService
    oktolab.hub_guid_contact_transformer.class: Oktolab\Bundle\RentBundle\Form\DataTransformer\HubGuidToContactTransformer

    # upload service-classes
    oktolab.upload_manager.class:             Oktolab\Bundle\RentBundle\Model\UploadManager
    oktolab.upload_listener.class:            Oktolab\Bundle\RentBundle\EventListener\UploadListener
    oktolab.upload_name_manager.class:        Oktolab\Bundle\RentBundle\Model\UploadNameManager

    # hub authentication service-classes
    oktolab.hub_user_provider.class:            Oktolab\Bundle\RentBundle\Model\HubUserProvider
    oktolab.hub_authentication_provider.class:  Oktolab\Bundle\RentBundle\Model\HubAuthenticationProvider
    oktolab.hub_security_listener.class:        Oktolab\Bundle\RentBundle\Model\SecurityListener
    oktolab.hub_auth_service.class:             Oktolab\Bundle\RentBundle\Model\HubAuthService
    oktolab.hub_search_service.class:           Oktolab\Bundle\RentBundle\Model\HubSearchService

services:
    oktolab.presavelistener:
        class:      %oktolab.presavelistener.class%
        arguments:  [ @?logger ]
        tags:
            - { name: logger, channel: main }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    oktolab.postsavelistener:
        class:      %oktolab.postsavelistener.class%
        arguments:  [ @?logger ]
        tags:
            - { name: logger, channel: main }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }

    oktolab.upload_manager:
        class:      %oktolab.upload_manager.class%
        arguments: [ %oktolab.upload_dir%, %oktolab.web_dir%, @oneup_uploader.orphanage_manager ]

    oktolab.upload_listener:
        class:      %oktolab.upload_listener.class%
        arguments:  [ @oktolab.upload_manager, @oneup_uploader.orphanage_manager ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    oktolab.upload_name_manager:
        class:    %oktolab.upload_name_manager.class%

    oktolab.twig.attachment.extension:
        class:      %oktolab.twig.attachment.extension.class%
        arguments:  [ @service_container ]
        tags:
            - { name: twig.extension }

    oktolab.twig.pager.extension:
        class:      %oktolab.twig.pager.extension.class%
        arguments:  [ @translator, @router ]
        tags:
            - { name: twig.extension }

    oktolab.item_import_manager:
        class:      %oktolab.item_import_manager.class%
        arguments:  [ @doctrine.orm.entity_manager, @validator, @oktolab.item_csv_importer ]

    oktolab.item_csv_importer:
        class:      %oktolab.item_csv_importer.class%
        arguments:  [ @doctrine.orm.entity_manager ]

    oktolab.hub_auth_service:
        class:      %oktolab.hub_auth_service.class%
        arguments:  [ %oktolab.hub_api_auth_url% ]

    oktolab.hub_search_service:
        class:      %oktolab.hub_search_service.class%
        arguments:  [ %oktolab.hub_api_search_url% ]

    oktolab.hub_user_provider:
        class:      %oktolab.hub_user_provider.class%
        arguments:  [ @doctrine.orm.entity_manager, @oktolab.hub_search_service , @oktolab.hub_auth_service ]

    oktolab.hub_authentication_provider:
        class:      %oktolab.hub_authentication_provider.class%
        arguments:  [ @oktolab.hub_user_provider ]

    oktolab.hub_security_listener:
        class:     %oktolab.hub_security_listener.class%
        arguments: [ @security.context, @oktolab.hub_authentication_provider ]

    # Global Oktolab-Cache. See Doctrine\Common\Cache for more details
    oktolab.cache:
        class:      %oktolab.cache.class%
        arguments:  [ %kernel.cache_dir% ]

    oktolab.contact_provider:
        class:      %oktolab.contact_provider.class%
        arguments:  [ @doctrine.orm.entity_manager, %oktolab.hub_api_search_url% ]

    oktolab.costunit_provider:
        class:      %oktolab.costunit_provider.class%
        arguments:  [ @doctrine.orm.entity_manager, @oktolab.hub_fetch_service, %oktolab.flow_api_costunit_url% ]

    oktolab.hub_fetch_service:
        class:      %oktolab.hub_fetch_service.class%
        arguments:  [ @doctrine.orm.entity_manager, %oktolab.hub_fetch_url% ]

    oktolab.hub_guid_contact_transformer:
        class:      %oktolab.hub_guid_contact_transformer.class%
        arguments:  [ @oktolab.hub_fetch_service ]
