parameters:
  oktolab.cache.class: Doctrine\Common\Cache\ArrayCache

services:
    oktolab.faker.provider.item:
      class: Oktolab\Bundle\RentBundle\Util\Faker\Provider\Item
      arguments: [@faker.generator]
      tags:
        - { name: bazinga_faker.provider }
