parameters:
    # common service-classes
    oktolab.cache.class:                      Doctrine\Common\Cache\PhpFileCache
    oktolab.orm.object_repository.class:      Doctrine\Common\Persistence\ObjectRepository
    oktolab.presavelistener.class:            Oktolab\Bundle\RentBundle\EventListener\LogListener
    oktolab.postsavelistener.class:           Oktolab\Bundle\RentBundle\EventListener\LogListener
    oktolab.twig.attachment.extension.class:  Oktolab\Bundle\RentBundle\Extension\AttachmentExtension
    oktolab.twig.pager.extension.class:       Oktolab\Bundle\RentBundle\Extension\AuiPaginationExtension
    oktolab.twig.weekdayToString.extension.class:       Oktolab\Bundle\RentBundle\Extension\WeekdaysToStringExtension
    oktolab.item_import_manager.class:        Oktolab\Bundle\RentBundle\Model\ItemImportManager
    oktolab.item_csv_importer.class:          Oktolab\Bundle\RentBundle\Model\ItemCsvParser
    oktolab.contact_provider.class:           Oktolab\Bundle\RentBundle\Model\ContactProvider
    oktolab.costunit_provider.class:          Oktolab\Bundle\RentBundle\Model\CostUnitProvider
    oktolab.hub_fetch_service.class:          Oktolab\Bundle\RentBundle\Model\HubFetchService
    oktolab.hub_guid_contact_transformer.class: Oktolab\Bundle\RentBundle\Form\DataTransformer\HubGuidToContactTransformer

    # upload service-classes
    oktolab.upload_manager.class:             Oktolab\Bundle\RentBundle\Model\UploadManager
    oktolab.upload_listener.class:            Oktolab\Bundle\RentBundle\EventListener\UploadListener
    oktolab.upload_name_manager.class:        Oktolab\Bundle\RentBundle\Model\UploadNameManager

    # hub authentication service-classes
    oktolab.hub_user_provider.class:            Oktolab\Bundle\RentBundle\Model\HubUserProvider
    oktolab.hub_authentication_provider.class:  Oktolab\Bundle\RentBundle\Model\HubAuthenticationProvider
    oktolab.hub_security_listener.class:        Oktolab\Bundle\RentBundle\Model\SecurityListener
    oktolab.hub_auth_service.class:             Oktolab\Bundle\RentBundle\Model\HubAuthService
    oktolab.hub_search_service.class:           Oktolab\Bundle\RentBundle\Model\HubSearchService

    # event management service-classes
    oktolab.event_manager.class:                       Oktolab\Bundle\RentBundle\Model\Event\EventManager
    oktolab.event_calendar_inventory_aggregator.class: Oktolab\Bundle\RentBundle\Model\Event\Calendar\InventoryAggregator
    oktolab.event_calendar_inventory.class:            Oktolab\Bundle\RentBundle\Model\Event\Calendar\InventoryTransformer
    oktolab.event_calendar_timeblock_aggregator.class: Oktolab\Bundle\RentBundle\Model\Event\Calendar\TimeblockAggregator
    oktolab.event_calendar_timeblock.class:            Oktolab\Bundle\RentBundle\Model\Event\Calendar\TimeblockTransformer
    oktolab.event_calendar_event_aggregator.class:     Oktolab\Bundle\RentBundle\Model\Event\Calendar\EventAggregator
    oktolab.event_calendar_event.class:                Oktolab\Bundle\RentBundle\Model\Event\Calendar\EventTransformer
    oktolab.inventory_transformer_cache_listener:      Oktolab\Bundle\RentBundle\EventListener\InventoryTransformerCacheListener

services:
    oktolab.presavelistener:
        class:      %oktolab.presavelistener.class%
        arguments:  [ @?logger ]
        tags:
            - { name: logger, channel: main }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    oktolab.postsavelistener:
        class:      %oktolab.postsavelistener.class%
        arguments:  [ @?logger ]
        tags:
            - { name: logger, channel: main }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }

    oktolab.inventory_transformer_cache_listener:
        class: %oktolab.inventory_transformer_cache_listener%
        arguments: [ @oktolab.cache ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postUpdate }

    oktolab.upload_manager:
        class:      %oktolab.upload_manager.class%
        arguments: [ %oktolab.upload_dir%, %oktolab.web_dir%, @oneup_uploader.orphanage_manager ]

    oktolab.upload_listener:
        class:      %oktolab.upload_listener.class%
        arguments:  [ @oktolab.upload_manager, @oneup_uploader.orphanage_manager ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    oktolab.upload_name_manager:
        class:    %oktolab.upload_name_manager.class%

    oktolab.twig.attachment.extension:
        class:      %oktolab.twig.attachment.extension.class%
        arguments:  [ @service_container ]
        tags:
            - { name: twig.extension }

    oktolab.twig.pager.extension:
        class:      %oktolab.twig.pager.extension.class%
        arguments:  [ @translator, @router ]
        tags:
            - { name: twig.extension }

    oktolab.twig.weekdayToString.extension:
        class:      %oktolab.twig.weekdayToString.extension.class%
        arguments:  [ @translator]
        tags:
            - { name: twig.extension }

    oktolab.orm.event_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Event ]

    oktolab.orm.item_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Inventory\Item ]

    oktolab.orm.set_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Inventory\Set ]

    oktolab.orm.category_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Inventory\Category ]

    oktolab.orm.timeblock_repository:
        class:            %oktolab.orm.object_repository.class%
        factory_service:  doctrine
        factory_method:   getRepository
        arguments:        [ OktolabRentBundle:Timeblock ]

    oktolab.event_manager:
        class:      %oktolab.event_manager.class%
        arguments:  [ @doctrine.orm.entity_manager, @?logger ]
        calls:
            - [ addRepository, [ "Event", @oktolab.orm.event_repository ] ]
            - [ addRepository, [ "Item", @oktolab.orm.item_repository ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]

    oktolab.item_import_manager:
        class:      %oktolab.item_import_manager.class%
        arguments:  [ @doctrine.orm.entity_manager, @validator, @oktolab.item_csv_importer ]

    oktolab.item_csv_importer:
        class:      %oktolab.item_csv_importer.class%
        arguments:  [ @doctrine.orm.entity_manager ]

    oktolab.hub_auth_service:
        class:      %oktolab.hub_auth_service.class%
        arguments:  [ %oktolab.hub_api_auth_url% ]

    oktolab.hub_search_service:
        class:      %oktolab.hub_search_service.class%
        arguments:  [ %oktolab.hub_api_search_url% ]

    oktolab.hub_user_provider:
        class:      %oktolab.hub_user_provider.class%
        arguments:  [ @doctrine.orm.entity_manager, @oktolab.hub_search_service , @oktolab.hub_auth_service ]

    oktolab.hub_authentication_provider:
        class:      %oktolab.hub_authentication_provider.class%
        arguments:  [ @oktolab.hub_user_provider ]

    oktolab.hub_security_listener:
        class:     %oktolab.hub_security_listener.class%
        arguments: [ @security.context, @oktolab.hub_authentication_provider ]

    oktolab.event_calendar_inventory_aggregator:
        class:  %oktolab.event_calendar_inventory_aggregator.class%
        calls:
            - [ addRepository, [ "Set", @oktolab.orm.set_repository ] ]
            - [ addRepository, [ "Item", @oktolab.orm.item_repository ] ]
            - [ addRepository, [ "Category", @oktolab.orm.category_repository ] ]

    oktolab.event_calendar_inventory:
        class:      %oktolab.event_calendar_inventory.class%
        arguments:  [ @oktolab.event_calendar_inventory_aggregator, @oktolab.cache ]

    oktolab.event_calendar_timeblock_aggregator:
        class:  %oktolab.event_calendar_timeblock_aggregator.class%
        calls:
            - [ addRepository, [ "Timeblock", @oktolab.orm.timeblock_repository ] ]

    oktolab.event_calendar_timeblock:
        class:      %oktolab.event_calendar_timeblock.class%
        arguments:  [ @oktolab.event_calendar_timeblock_aggregator, @oktolab.event_calendar_timeblock_cache ]

    # 'Cause there is no way to delete Keys by Regex or Pre-/Suffix.
    oktolab.event_calendar_timeblock_cache:
        class:      %oktolab.cache.class%
        arguments:  [ %kernel.cache_dir% ]

    oktolab.event_calendar_event_aggregator:
        class: %oktolab.event_calendar_event_aggregator.class%
        calls:
            - [ addRepository, [ "Event", @oktolab.orm.event_repository ] ]

    oktolab.event_calendar_event:
        class:      %oktolab.event_calendar_event.class%
        arguments:  [ @oktolab.event_calendar_event_aggregator, @router, @oktolab.event_manager, @oktolab.cache ]

    # Global Oktolab-Cache. See Doctrine\Common\Cache for more details
    oktolab.cache:
        class:      %oktolab.cache.class%
        arguments:  [ %kernel.cache_dir% ]

    oktolab.contact_provider:
        class:      %oktolab.contact_provider.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %oktolab.hub_api_search_url%

    oktolab.costunit_provider:
        class:      %oktolab.costunit_provider.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oktolab.hub_fetch_service
            - %oktolab.flow_api_costunit_url%

    oktolab.hub_fetch_service:
        class:      %oktolab.hub_fetch_service.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %oktolab.hub_fetch_url%

    oktolab.hub_guid_contact_transformer:
        class:      %oktolab.hub_guid_contact_transformer.class%
        arguments: [@oktolab.hub_fetch_service]
