parameters:
    oktolab.event_manager.class:                       Oktolab\Bundle\RentBundle\Model\Event\EventManager
    oktolab.event_calendar_inventory_aggregator.class: Oktolab\Bundle\RentBundle\Model\Event\Calendar\InventoryAggregator
    oktolab.event_calendar_inventory.class:            Oktolab\Bundle\RentBundle\Model\Event\Calendar\InventoryTransformer
    oktolab.cache.class:                               Doctrine\Common\Cache\PhpFileCache

services:
    oktolab.presavelistener:
        class: Oktolab\Bundle\RentBundle\EventListener\LogListener
        arguments: [@?logger]
        tags:
            - { name: logger, channel: main}
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    oktolab.postsavelistener:
        class: Oktolab\Bundle\RentBundle\EventListener\LogListener
        arguments: [@?logger]
        tags:
            - { name: logger, channel: main}
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }

    oktolab.upload_manager:
        class: Oktolab\Bundle\RentBundle\Model\UploadManager
        arguments:
            - %oktolab.upload_dir%
            - %oktolab.web_dir%
            - @doctrine.orm.entity_manager
            - @oneup_uploader.orphanage_manager

    oktolab.upload_listener:
        class: Oktolab\Bundle\RentBundle\EventListener\UploadListener
        arguments:
            - @oneup_uploader.orphanage_manager
            - @oktolab.upload_manager
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: prePersist }

    oktolab.upload_name_manager:
        class: Oktolab\Bundle\RentBundle\Model\UploadNameManager

    oktolab.twig.attachment.extension:
        class:  Oktolab\Bundle\RentBundle\Extension\AttachmentExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    oktolab.orm.event_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ OktolabRentBundle:Event ]

    oktolab.orm.item_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ OktolabRentBundle:Inventory\Item ]

    oktolab.orm.set_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ OktolabRentBundle:Inventory\Set ]

    oktolab.orm.category_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ OktolabRentBundle:Inventory\Category ]

    oktolab.event_manager:
        class: %oktolab.event_manager.class%
        arguments:  [ @doctrine.orm.entity_manager, @?logger ]
        calls:
            - [ addRepository, [ "Event", @oktolab.orm.event_repository ] ]
            - [ addRepository, [ "Item", @oktolab.orm.item_repository ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]

    oktolab.item_import_manager:
      class: Oktolab\Bundle\RentBundle\Model\ItemImportManager
      arguments:
          - @doctrine.orm.entity_manager
          - @validator
          - @oktolab.item_csv_importer

    oktolab.item_csv_importer:
      class: Oktolab\Bundle\RentBundle\Model\ItemCsvParser
      arguments:  [ @doctrine.orm.entity_manager ]

    oktolab.hub_user_provider:
      class: Oktolab\Bundle\RentBundle\Model\HubUserProvider
      arguments:  [ @doctrine.orm.entity_manager, %oktolab.hub_api_search_url%, %oktolab.hub_api_auth_url% ]

    oktolab.hub_authentication_provider:
      class:  Oktolab\Bundle\RentBundle\Model\HubAuthenticationProvider
      arguments:  [ @oktolab.hub_user_provider ]

    oktolab.hub_security_listener:
      class:  Oktolab\Bundle\RentBundle\Model\SecurityListener
      arguments: [ @security.context , @oktolab.hub_authentication_provider ]

    oktolab.event_calendar_inventory_aggregator:
        class: %oktolab.event_calendar_inventory_aggregator.class%
        calls:
            - [ addRepository, [ "Set", @oktolab.orm.set_repository ] ]
            - [ addRepository, [ "Item", @oktolab.orm.item_repository ] ]
            - [ addRepository, [ "Category", @oktolab.orm.category_repository ] ]

    oktolab.event_calendar_inventory:
        class: %oktolab.event_calendar_inventory.class%
        arguments: [ @oktolab.event_calendar_inventory_aggregator, @oktolab.cache ]

    oktolab.cache:
        class: %oktolab.cache.class%
        arguments: [ %kernel.cache_dir% ]
